/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/movies': RouteRecordInfo<
      '/movies',
      '/movies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/music': RouteRecordInfo<
      '/music',
      '/music',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search': RouteRecordInfo<
      '/search',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shows': RouteRecordInfo<
      '/shows',
      '/shows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/title/[id]': RouteRecordInfo<
      '/title/[id]',
      '/title/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/watch/[id]': RouteRecordInfo<
      '/watch/[id]',
      '/watch/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/movies.vue': {
      routes:
        | '/movies'
      views:
        | never
    }
    'src/pages/music.vue': {
      routes:
        | '/music'
      views:
        | never
    }
    'src/pages/search.vue': {
      routes:
        | '/search'
      views:
        | never
    }
    'src/pages/shows.vue': {
      routes:
        | '/shows'
      views:
        | never
    }
    'src/pages/title/[id].vue': {
      routes:
        | '/title/[id]'
      views:
        | never
    }
    'src/pages/watch/[id].vue': {
      routes:
        | '/watch/[id]'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
